### ISSUE TITLE
Swagger Docs for complex types

### ISSUE THREAD

**Issue by seanoshea** [rgbycch/rgbycch-rest#11]
Looking at the swagger docs, it appears that there's a `player-creation-rest-controller` with one `GET` method for player creation? Should this not be a `POST` for creating a new player?

Either way, there are references to `rgbycch.model.playerposition.pp10` in the middle of the swagger docs. Looks like we'd need some way of telling swagger about the `Position` class?

**Comment by gffny** [comment]
I'll look at Swagger Documentation for the domain models. I'll take a look at the player-creation-rest-controller

**Comment by gffny** [comment]
The method is a POST but it was incorrectly documented as a GET

**Comment by seanoshea** [comment]
I was mixed up on the complex types stuff. Looks like player position is just an int enum? But, the swagger docs don't appear to pick up on that fact and just report it as a `rgbycch.model.playerposition.pp10` - maybe it uses the result of the `toString()` method or something?

**Comment by gffny** [comment]
Yeah, I think it is the toString override that I have written. I wanted 
to have a localisation for different positions, so in England a #9 is a 
scrum-half but in NZ the position is called halfback. In SA, #6 is 
open-side flanker, but in Ireland the position is blindside flanker. we 
can figure something out for that later

**Comment by seanoshea** [comment]
Perhaps we shouldn't have it as a enum then? And just use a normal class. i.e - a class with a number property and a position name?
