### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by seanoshea** [rgbycch/rgbycch-rest#4]
Dunno whether integrating with findbugs/pmd is still the done thing with Java projects, but might be worthwhile looking into integrating these tools with the CI flow for the REST API at the start of the project? Or, do you reckon this is overkill?

**Comment by gffny** [comment]
I really like a tool called SonarQube. It would be great to integrate it into our CI. I don't think they have a cloud based offering, so we could either set it up on our AWS environment or look for another similar tool

**Comment by seanoshea** [comment]
Never used SonarQube myself. A quick bit o Googling brings up https://gist.github.com/lukespragg/11309089?

**Comment by gffny** [comment]
Looks good to me, but I'll still need to set up that database. I can do that this weekend.

**Comment by seanoshea** [comment]
Some chat between me and one of the SonarQube fellas: https://twitter.com/benzonico/status/624112701195845632

**Comment by gffny** [comment]
A hosted solution would be handy. You should be able to get it working locally but we'd want to have something available on the internet to integrate it with travis

**Comment by seanoshea** [comment]
Yeah - it'd be nice alright. FWIW, PMD and Findbugs are all local as well and don't offer hosted solutions for integration with travis-ci. Maybe this is more hassle than it's worth and we should crack on with actually developing out the API? Or, if you feel strongly about it & think we should tackle this straight off the bat, fire away with the SonarQube integration.

**Comment by gffny** [comment]
I've created a DB instance on AWS that we can use to set up the database. The travis plugin can be used to push the data to that database. I'm not sure if we'd want to run it on each build; maybe on a per-release basis
