### ISSUE TITLE
Swift-based cocoapod for Communicating with rgbycch API

### ISSUE THREAD

**Issue by gffny** [rgbycch/rgbycch-rest#6]
FROM @seanoshea: Should be fully documented and unit tested

**Comment by gffny** [comment]
Could use something like http://swagger.io to document the APIs

**Comment by seanoshea** [comment]
Little bit confused on this one. Are you suggesting that the swift code for integrating with the API should live in the `rgbycch` repo? Would have thought that it would probably belong in the iOS project for now.

Definitely up for using swagger to host docs for the API. http://petstore.swagger.io is one example. Wonder if there's a simple hosting solution for the docs available for open source projects. Would be nice to have the docs updated every time the project builds & have it automatically generated from the java code powering the API.

**Comment by seanoshea** [comment]
Closing this as https://github.com/rgbycch/rgbycch_swift_api was created for the swift API client.
